var gegevensMarker = [
['s Heerenhoek', 51.469914, 3.775196, <?php if(isset($mstations['s Heerenhoek'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Aalsmeer', 52.261423, 4.772008, <?php if(isset($mstations['Aalsmeer'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Aalten', 51.91558, 6.564545, <?php if(isset($mstations['Aalten'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Abcoude', 52.262313, 4.977068, <?php if(isset($mstations['Abcoude'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Akkrum', 53.053094, 5.819705, <?php if(isset($mstations['Akkrum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Almelo', 52.34601, 6.664011, <?php if(isset($mstations['Almelo'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Almen', 52.160449, 6.32254, <?php if(isset($mstations['Almen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Amerongen', 51.993363, 5.460005, <?php if(isset($mstations['Amerongen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Ammerzoden', 51.750572, 5.213427, <?php if(isset($mstations['Ammerzoden'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Amsterdam', 52.369944, 4.917339, <?php if(isset($mstations['Amsterdam'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Andel', 51.786181, 5.053867, <?php if(isset($mstations['Andel'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Anjum', 53.383993, 6.138629, <?php if(isset($mstations['Anjum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Anna Jacoba Polder', 51.636092, 4.130457, <?php if(isset($mstations['Anna Jacoba Polder'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Anna Paulowna', 52.8639, 4.837793, <?php if(isset($mstations['Anna Paulowna'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Apeldoorn', 52.216775, 5.943256, <?php if(isset($mstations['Apeldoorn'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Appelscha', 52.960218, 6.339663, <?php if(isset($mstations['Appelscha'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Arcen', 51.478358, 6.178927, <?php if(isset($mstations['Arcen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Arnhem', 52.001139, 5.926016, <?php if(isset($mstations['Arnhem'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Assen', 53.002856, 6.593855, <?php if(isset($mstations['Assen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Assendelft', 52.46789, 4.724989, <?php if(isset($mstations['Assendelft'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Barendrecht', 51.855544, 4.545309, <?php if(isset($mstations['Barendrecht'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Barneveld', 52.137064, 5.562486, <?php if(isset($mstations['Barneveld'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Beek', 50.922955, 5.81385, <?php if(isset($mstations['Beek'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Beekbergen', 52.16278, 5.957198, <?php if(isset($mstations['Beekbergen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Benschop', 52.001508, 4.935767, <?php if(isset($mstations['Benschop'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Bergen (Nh)', 52.683313, 4.67738, <?php if(isset($mstations['Bergen (Nh)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Bergen op Zoom', 51.502468, 4.249381, <?php if(isset($mstations['Bergen op Zoom'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Bergschenhoek', 51.981047, 4.499285, <?php if(isset($mstations['Bergschenhoek'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Bergumerdam', 53.178031, 6.015393, <?php if(isset($mstations['Bergumerdam'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Berkhout', 52.64, 4.98, <?php if(isset($mstations['Berkhout'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Biddinghuizen', 52.45136, 5.696124, <?php if(isset($mstations['Biddinghuizen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Biervliet', 51.333907, 3.693885, <?php if(isset($mstations['Biervliet'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Blokzijl', 52.729035, 5.949738, <?php if(isset($mstations['Blokzijl'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Borculo', 52.095743, 6.525504, <?php if(isset($mstations['Borculo'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Boskoop', 52.081186, 4.686955, <?php if(isset($mstations['Boskoop'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Boxtel', 51.579905, 5.329496, <?php if(isset($mstations['Boxtel'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Breskens', 51.394628, 3.547919, <?php if(isset($mstations['Breskens'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Brielle', 51.897014, 4.152232, <?php if(isset($mstations['Brielle'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Brouwershaven', 51.732043, 3.881674, <?php if(isset($mstations['Brouwershaven'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Buchten', 51.039858, 5.800675, <?php if(isset($mstations['Buchten'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Cabauw', 51.97, 4.93, <?php if(isset($mstations['Cabauw'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Cadzand', 51.374305, 3.405084, <?php if(isset($mstations['Cadzand'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Callantsoog', 52.854224, 4.704299, <?php if(isset($mstations['Callantsoog'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Capelle (Nb)', 51.678094, 4.982371, <?php if(isset($mstations['Capelle (Nb)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Castricum', 52.548336, 4.650066, <?php if(isset($mstations['Castricum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Chaam', 51.50686, 4.868664, <?php if(isset($mstations['Chaam'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Culemborg', 51.930359, 5.227272, <?php if(isset($mstations['Culemborg'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['De Bilt', 52.101065, 5.182877, <?php if(isset($mstations['De Bilt'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['De Cocksdorp', 53.160629, 4.878886, <?php if(isset($mstations['De Cocksdorp'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['De Haukes', 52.882306, 4.94155, <?php if(isset($mstations['De Haukes'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['De Koog', 53.097242, 4.775125, <?php if(isset($mstations['De Koog'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['De Kooy', 52.917603, 4.792514, <?php if(isset($mstations['De Kooy'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Dedemsvaart', 52.590806, 6.449728, <?php if(isset($mstations['Dedemsvaart'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Deelen', 52.064246, 5.883026, <?php if(isset($mstations['Deelen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Delft', 52.006947, 4.367686, <?php if(isset($mstations['Delft'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Delfzijl', 53.32249, 6.932987, <?php if(isset($mstations['Delfzijl'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Den Bommel', 51.71871, 4.301832, <?php if(isset($mstations['Den Bommel'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Den Burg', 53.052463, 4.805583, <?php if(isset($mstations['Den Burg'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Den Oever', 52.927537, 5.030312, <?php if(isset($mstations['Den Oever'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Denekamp', 52.37742, 7.032113, <?php if(isset($mstations['Denekamp'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Deurne', 51.453431, 5.775651, <?php if(isset($mstations['Deurne'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Deventer', 52.260073, 6.2221, <?php if(isset($mstations['Deventer'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Dinther', 51.642795, 5.488333, <?php if(isset($mstations['Dinther'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Dirksland', 51.743458, 4.084029, <?php if(isset($mstations['Dirksland'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Doetinchem', 51.980821, 6.304235, <?php if(isset($mstations['Doetinchem'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Dokkum', 53.321945, 5.987477, <?php if(isset($mstations['Dokkum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Doorn', 52.056288, 5.328884, <?php if(isset($mstations['Doorn'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Drachten', 53.114632, 6.104086, <?php if(isset($mstations['Drachten'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Dronten', 52.540699, 5.858893, <?php if(isset($mstations['Dronten'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Duiven', 51.964755, 6.012884, <?php if(isset($mstations['Duiven'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Dwingelo', 52.824822, 6.410897, <?php if(isset($mstations['Dwingelo'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Echt', 51.093326, 5.91535, <?php if(isset($mstations['Echt'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Edam', 52.514192, 5.048388, <?php if(isset($mstations['Edam'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Eelde', 53.119803, 6.582171, <?php if(isset($mstations['Eelde'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Eemnes', 52.271954, 5.269999, <?php if(isset($mstations['Eemnes'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Eenrum', 53.363507, 6.468753, <?php if(isset($mstations['Eenrum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Eerbeek', 52.108233, 6.073283, <?php if(isset($mstations['Eerbeek'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Eernewoude', 53.133473, 5.940039, <?php if(isset($mstations['Eernewoude'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Eersel', 51.346143, 5.258025, <?php if(isset($mstations['Eersel'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Eext', 53.001428, 6.727893, <?php if(isset($mstations['Eext'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Eindhoven (Vb)', 51.445086, 5.415972, <?php if(isset($mstations['Eindhoven (Vb)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Elburg', 52.441954, 5.828425, <?php if(isset($mstations['Elburg'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Ell', 51.2, 5.76, <?php if(isset($mstations['Ell'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Elspeet', 52.289324, 5.782938, <?php if(isset($mstations['Elspeet'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Emmeloord', 52.702782, 5.771865, <?php if(isset($mstations['Emmeloord'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Emmen', 52.783865, 6.88429, <?php if(isset($mstations['Emmen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Enkhuizen', 52.712346, 5.283624, <?php if(isset($mstations['Enkhuizen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Enschede', 52.208277, 6.908804, <?php if(isset($mstations['Enschede'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Epe', 52.342307, 6.003526, <?php if(isset($mstations['Epe'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Epen (Nieuw) (L)', 50.760753, 5.911564, <?php if(isset($mstations['Epen (Nieuw) (L)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Esbeek', 51.435845, 5.14272, <?php if(isset($mstations['Esbeek'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Ezinge', 53.29177, 6.451956, <?php if(isset($mstations['Ezinge'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Ezumazijl', 53.356945, 6.153176, <?php if(isset($mstations['Ezumazijl'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Finsterwolde', 53.203273, 7.10834, <?php if(isset($mstations['Finsterwolde'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Formerum', 53.395292, 5.297018, <?php if(isset($mstations['Formerum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Frederiksoord', 52.844497, 6.188709, <?php if(isset($mstations['Frederiksoord'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Geldermalsen', 51.876481, 5.271029, <?php if(isset($mstations['Geldermalsen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Gemert', 51.543609, 5.675513, <?php if(isset($mstations['Gemert'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Gendringen', 51.863639, 6.345402, <?php if(isset($mstations['Gendringen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Giersbergen', 51.660588, 5.155961, <?php if(isset($mstations['Giersbergen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Gieterveen', 53.026984, 6.847934, <?php if(isset($mstations['Gieterveen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Giethoorn', 52.71943, 6.068019, <?php if(isset($mstations['Giethoorn'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Gilze-Rijen', 51.57002, 4.925639, <?php if(isset($mstations['Gilze-Rijen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Ginneken', 51.551232, 4.752812, <?php if(isset($mstations['Ginneken'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Goedereede', 51.814002, 3.965961, <?php if(isset($mstations['Goedereede'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Gorinchem', 51.839882, 4.980918, <?php if(isset($mstations['Gorinchem'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Gorredijk', 52.99808, 6.057479, <?php if(isset($mstations['Gorredijk'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Gouda', 52.009455, 4.717207, <?php if(isset($mstations['Gouda'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Groningen', 53.182692, 6.583907, <?php if(isset($mstations['Groningen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Groot Ammers', 51.92917, 4.834719, <?php if(isset($mstations['Groot Ammers'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Haamstede', 51.684963, 3.72415, <?php if(isset($mstations['Haamstede'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Hamersveld', 52.13719, 5.416419, <?php if(isset($mstations['Hamersveld'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Harderwijk', 52.361683, 5.607415, <?php if(isset($mstations['Harderwijk'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Harlingen', 53.179669, 5.432081, <?php if(isset($mstations['Harlingen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Harskamp', 52.154648, 5.737905, <?php if(isset($mstations['Harskamp'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Heeg', 52.963833, 5.595572, <?php if(isset($mstations['Heeg'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Heemstede', 52.341547, 4.638828, <?php if(isset($mstations['Heemstede'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Heerde', 52.378099, 6.033397, <?php if(isset($mstations['Heerde'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Heibloem (L)', 51.2912, 5.888961, <?php if(isset($mstations['Heibloem (L)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Heiloo', 52.593786, 4.737856, <?php if(isset($mstations['Heiloo'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Heino', 52.439489, 6.269604, <?php if(isset($mstations['Heino'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Hellendoorn', 52.384126, 6.444769, <?php if(isset($mstations['Hellendoorn'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Helmond', 51.462867, 5.603052, <?php if(isset($mstations['Helmond'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Hendrik Ido Ambacht', 51.829266, 4.647351, <?php if(isset($mstations['Hendrik Ido Ambacht'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Hengelo (O)', 52.263987, 6.764206, <?php if(isset($mstations['Hengelo (O)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Hengelo', 52.061706, 6.305892, <?php if(isset($mstations['Hengelo'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Herbayum', 53.179618, 5.506867, <?php if(isset($mstations['Herbayum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Herwen', 51.892357, 6.099041, <?php if(isset($mstations['Herwen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Herwijnen', 51.822379, 5.155132, <?php if(isset($mstations['Herwijnen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Heumen', 51.767817, 5.836304, <?php if(isset($mstations['Heumen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Hoek van Holland', 51.986879, 4.149758, <?php if(isset($mstations['Hoek van Holland'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Hollum', 53.430993, 5.64297, <?php if(isset($mstations['Hollum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Holten', 52.303117, 6.457502, <?php if(isset($mstations['Holten'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Honselersdijk', 52.00588, 4.25119, <?php if(isset($mstations['Honselersdijk'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Hoofddorp', 52.287807, 4.669046, <?php if(isset($mstations['Hoofddorp'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Hoogerheide', 51.431117, 4.308687, <?php if(isset($mstations['Hoogerheide'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Hoogeveen', 52.707352, 6.482142, <?php if(isset($mstations['Hoogeveen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Hoogkarspel', 52.685224, 5.165379, <?php if(isset($mstations['Hoogkarspel'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Hoogwoud', 52.729591, 4.957905, <?php if(isset($mstations['Hoogwoud'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Hoorn (Nh)', 52.648997, 5.04735, <?php if(isset($mstations['Hoorn (Nh)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Hoorn (Terschelling)', 53.39, 5.35, <?php if(isset($mstations['Hoorn (Terschelling)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Hulshorst', 52.361486, 5.695498, <?php if(isset($mstations['Hulshorst'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Hupsel', 52.067599, 6.641471, <?php if(isset($mstations['Hupsel'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['IJsselmuiden', 52.576191, 5.962538, <?php if(isset($mstations['IJsselmuiden'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['IJsselsteyn (L)', 51.488945, 5.891141, <?php if(isset($mstations['IJsselsteyn (L)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Joure', 52.963235, 5.818813, <?php if(isset($mstations['Joure'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Kapelle', 51.481158, 3.947572, <?php if(isset($mstations['Kapelle'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Kapellebrug', 51.257524, 4.040569, <?php if(isset($mstations['Kapellebrug'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Katwijk aan den Rijn', 52.187056, 4.407442, <?php if(isset($mstations['Katwijk aan den Rijn'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Kerkwerve', 51.677941, 3.869014, <?php if(isset($mstations['Kerkwerve'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Klazienaveen', 52.737397, 7.001172, <?php if(isset($mstations['Klazienaveen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Kloosterzande', 51.38317, 4.022497, <?php if(isset($mstations['Kloosterzande'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Klundert', 51.657712, 4.534537, <?php if(isset($mstations['Klundert'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Kolhorn', 52.792268, 4.897991, <?php if(isset($mstations['Kolhorn'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Kollum', 53.276179, 6.136751, <?php if(isset($mstations['Kollum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Kootwijk (Radio)', 52.17233, 5.825754, <?php if(isset($mstations['Kootwijk (Radio)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Kornwerderzand', 53.062853, 5.342459, <?php if(isset($mstations['Kornwerderzand'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Kortgene', 51.560555, 3.829672, <?php if(isset($mstations['Kortgene'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Krabbendijke', 51.438069, 4.107155, <?php if(isset($mstations['Krabbendijke'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Kreileroord', 52.864795, 5.090222, <?php if(isset($mstations['Kreileroord'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Krimpen aan de Lek', 51.891993, 4.617265, <?php if(isset($mstations['Krimpen aan de Lek'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Kuinre', 52.783398, 5.846683, <?php if(isset($mstations['Kuinre'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Laaghalen', 52.92258, 6.532152, <?php if(isset($mstations['Laaghalen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Laren', 52.244895, 5.19686, <?php if(isset($mstations['Laren'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Lauwersoog', 53.41, 6.2, <?php if(isset($mstations['Lauwersoog'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Leende', 51.328148, 5.530678, <?php if(isset($mstations['Leende'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Leeuwarden', 53.224021, 5.761524, <?php if(isset($mstations['Leeuwarden'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Leiden', 52.142705, 4.481463, <?php if(isset($mstations['Leiden'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Lelystad (Eendenweg)', 52.451672, 5.534311, <?php if(isset($mstations['Lelystad (Eendenweg)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Lemmer (Gemaal Buma)', 52.837757, 5.713692, <?php if(isset($mstations['Lemmer (Gemaal Buma)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Lettele', 52.268632, 6.280863, <?php if(isset($mstations['Lettele'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Lichtenvoorde', 51.99646, 6.566668, <?php if(isset($mstations['Lichtenvoorde'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Lievelde', 52.013681, 6.639961, <?php if(isset($mstations['Lievelde'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Lijnden (Nh)', 52.351219, 4.756086, <?php if(isset($mstations['Lijnden (Nh)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Lisse', 52.260076, 4.552313, <?php if(isset($mstations['Lisse'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Lochem', 52.15086, 6.395399, <?php if(isset($mstations['Lochem'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Loenen aan de Vecht', 52.208576, 5.036083, <?php if(isset($mstations['Loenen aan de Vecht'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Lunteren', 52.092051, 5.606085, <?php if(isset($mstations['Lunteren'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Maarheeze', 51.310086, 5.587988, <?php if(isset($mstations['Maarheeze'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Maasland', 51.969933, 4.2521, <?php if(isset($mstations['Maasland'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Maastricht', 50.91, 5.77, <?php if(isset($mstations['Maastricht'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Makkum', 53.062861, 5.402126, <?php if(isset($mstations['Makkum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Markelo', 52.239943, 6.485266, <?php if(isset($mstations['Markelo'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Marken (Nieuw)', 52.460455, 5.122367, <?php if(isset($mstations['Marken (Nieuw)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Marknesse', 52.693475, 5.860533, <?php if(isset($mstations['Marknesse'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Marum', 53.149365, 6.284029, <?php if(isset($mstations['Marum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Medemblik', 52.756993, 5.105765, <?php if(isset($mstations['Medemblik'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Megen', 51.822479, 5.56126, <?php if(isset($mstations['Megen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Middelburg', 51.485151, 3.587461, <?php if(isset($mstations['Middelburg'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Middelstum', 53.326129, 6.617908, <?php if(isset($mstations['Middelstum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Mill', 51.678093, 5.792037, <?php if(isset($mstations['Mill'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Nagele', 52.622035, 5.726857, <?php if(isset($mstations['Nagele'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Nes (Ameland)', 53.448599, 5.778532, <?php if(isset($mstations['Nes (Ameland)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Niekerk', 53.220779, 6.3454, <?php if(isset($mstations['Niekerk'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Nieuw Beerta', 53.20, 7.15, <?php if(isset($mstations['Nieuw Beerta'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Nieuw Buinen', 52.971764, 6.950298, <?php if(isset($mstations['Nieuw Buinen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Nieuw Helvoet', 51.833799, 4.124946, <?php if(isset($mstations['Nieuw Helvoet'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Nieuwendijk (Nb)', 51.767762, 4.923619, <?php if(isset($mstations['Nieuwendijk (Nb)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Nieuwolda', 53.249844, 6.990322, <?php if(isset($mstations['Nieuwolda'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Nijbeets', 53.061299, 5.998787, <?php if(isset($mstations['Nijbeets'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Nijkerk', 52.236028, 5.475041, <?php if(isset($mstations['Nijkerk'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Nijmegen', 51.848474, 5.895161, <?php if(isset($mstations['Nijmegen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Noorbeek', 50.770149, 5.812445, <?php if(isset($mstations['Noorbeek'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Noordgouwe', 51.697182, 3.969633, <?php if(isset($mstations['Noordgouwe'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Nuland', 51.723732, 5.41615, <?php if(isset($mstations['Nuland'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Numansdorp', 51.7377, 4.417202, <?php if(isset($mstations['Numansdorp'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Obdam (Nieuw)', 52.675382, 4.884507, <?php if(isset($mstations['Obdam (Nieuw)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oirschot', 51.507996, 5.329587, <?php if(isset($mstations['Oirschot'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oldebroek', 52.387669, 5.91602, <?php if(isset($mstations['Oldebroek'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oldeholtpade', 52.899236, 6.055961, <?php if(isset($mstations['Oldeholtpade'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Onnen', 53.154811, 6.672837, <?php if(isset($mstations['Onnen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oost Maarland', 50.797438, 5.713413, <?php if(isset($mstations['Oost Maarland'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oost Vlieland', 53.296076, 5.072262, <?php if(isset($mstations['Oost Vlieland'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oosterbeek', 52.010495, 5.838734, <?php if(isset($mstations['Oosterbeek'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oosterhout', 51.641747, 4.881568, <?php if(isset($mstations['Oosterhout'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oostvaardersdiep', 52.415704, 5.225524, <?php if(isset($mstations['Oostvaardersdiep'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oostvoorne', 51.905375, 4.093871, <?php if(isset($mstations['Oostvoorne'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oss', 51.7596, 5.532048, <?php if(isset($mstations['Oss'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oud Alblas', 51.856495, 4.690452, <?php if(isset($mstations['Oud Alblas'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Ouddorp', 51.821902, 3.878673, <?php if(isset($mstations['Ouddorp'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oudemirdum', 52.856119, 5.505979, <?php if(isset($mstations['Oudemirdum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Oudenbosch', 51.576716, 4.521632, <?php if(isset($mstations['Oudenbosch'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Overveen', 52.395182, 4.593846, <?php if(isset($mstations['Overveen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Ovezande', 51.425573, 3.819906, <?php if(isset($mstations['Ovezande'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Petten', 52.7641, 4.661257, <?php if(isset($mstations['Petten'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Philippine', 51.298784, 3.752549, <?php if(isset($mstations['Philippine'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Poortugaal', 51.854291, 4.38566, <?php if(isset($mstations['Poortugaal'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Purmerend', 52.513852, 4.945272, <?php if(isset($mstations['Purmerend'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Putten (Gld)', 52.235856, 5.606792, <?php if(isset($mstations['Putten (Gld)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Rotterdam-Waalhaven', 51.890603, 4.428434, <?php if(isset($mstations['Rotterdam-Waalhaven'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Rekken', 52.084607, 6.729495, <?php if(isset($mstations['Rekken'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Reuver', 51.281258, 6.075182, <?php if(isset($mstations['Reuver'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Rheezerveen', 52.562735, 6.567041, <?php if(isset($mstations['Rheezerveen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Rilland', 51.420861, 4.179529, <?php if(isset($mstations['Rilland'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Ritthem', 51.458636, 3.617292, <?php if(isset($mstations['Ritthem'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Roden', 53.148153, 6.433477, <?php if(isset($mstations['Roden'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Roelofarendsveen', 52.215635, 4.626311, <?php if(isset($mstations['Roelofarendsveen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Roermond', 51.183008, 5.959289, <?php if(isset($mstations['Roermond'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Roodeschool', 53.441103, 6.786751, <?php if(isset($mstations['Roodeschool'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Rotterdam', 51.95, 4.44, <?php if(isset($mstations['Rotterdam'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Rouveen', 52.610858, 6.184452, <?php if(isset($mstations['Rouveen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Ruinerwold', 52.718281, 6.245604, <?php if(isset($mstations['Ruinerwold'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Sappemeer', 53.154155, 6.732619, <?php if(isset($mstations['Sappemeer'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Schaesberg', 50.895007, 6.026791, <?php if(isset($mstations['Schaesberg'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Schagen', 52.79187, 4.809046, <?php if(isset($mstations['Schagen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Schellingwoude', 52.397175, 4.990513, <?php if(isset($mstations['Schellingwoude'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Scheveningen', 52.105282, 4.307054, <?php if(isset($mstations['Scheveningen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Schiermonnikoog', 53.473545, 6.185378, <?php if(isset($mstations['Schiermonnikoog'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Schinnen', 50.93172, 5.870829, <?php if(isset($mstations['Schinnen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Schinveld', 50.97613, 5.9852, <?php if(isset($mstations['Schinveld'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Schiphol', 52.3, 4.77, <?php if(isset($mstations['Schiphol'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Schoondijke', 51.358688, 3.549367, <?php if(isset($mstations['Schoondijke'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Schoonebeek', 52.684851, 6.895705, <?php if(isset($mstations['Schoonebeek'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Schoonlo', 52.902767, 6.709997, <?php if(isset($mstations['Schoonlo'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Sevenum', 51.398431, 6.019469, <?php if(isset($mstations['Sevenum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Siebengewald', 51.658673, 6.095363, <?php if(isset($mstations['Siebengewald'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Skrins', 53.116475, 5.656047, <?php if(isset($mstations['Skrins'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Sneek', 53.035635, 5.640639, <?php if(isset($mstations['Sneek'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Soest', 52.164144, 5.328744, <?php if(isset($mstations['Soest'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Soesterberg', 52.13, 5.27, <?php if(isset($mstations['Soesterberg'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Someren', 51.399755, 5.688973, <?php if(isset($mstations['Someren'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Spakenburg', 52.254036, 5.387206, <?php if(isset($mstations['Spakenburg'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['St Anna Parochie', 53.27818, 5.672046, <?php if(isset($mstations['St Anna Parochie'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['St Anthonis', 51.632819, 5.878297, <?php if(isset($mstations['St Anthonis'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['St Kruis', 51.276906, 3.495313, <?php if(isset($mstations['St Kruis'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Stavenisse', 51.589862, 4.016284, <?php if(isset($mstations['Stavenisse'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Stavoren', 52.883134, 5.357498, <?php if(isset($mstations['Stavoren'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Steenbergen (Nb)', 51.593152, 4.333701, <?php if(isset($mstations['Steenbergen (Nb)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Steenwijksmoer', 52.660502, 6.673136, <?php if(isset($mstations['Steenwijksmoer'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Stein (L)', 50.968094, 5.757325, <?php if(isset($mstations['Stein (L)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Stramproy', 51.183951, 5.716158, <?php if(isset($mstations['Stramproy'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Strijen', 51.765972, 4.590441, <?php if(isset($mstations['Strijen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Swifterbant', 52.559376, 5.623149, <?php if(isset($mstations['Swifterbant'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Ter Apel', 52.871123, 7.080382, <?php if(isset($mstations['Ter Apel'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Ternaard', 53.375928, 5.973204, <?php if(isset($mstations['Ternaard'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Terneuzen', 51.309324, 3.866923, <?php if(isset($mstations['Terneuzen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Tholen', 51.529001, 4.205481, <?php if(isset($mstations['Tholen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Tiel', 51.930453, 5.445363, <?php if(isset($mstations['Tiel'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Tilburg', 51.561654, 5.127622, <?php if(isset($mstations['Tilburg'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Tollebeek', 52.667221, 5.623728, <?php if(isset($mstations['Tollebeek'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Tubbergen', 52.398597, 6.783083, <?php if(isset($mstations['Tubbergen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Twenthe', 52.262189, 6.910648, <?php if(isset($mstations['Twenthe'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Ubachsberg', 50.850637, 5.912581, <?php if(isset($mstations['Ubachsberg'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Uithuizen', 53.379399, 6.679544, <?php if(isset($mstations['Uithuizen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Vaals', 50.778236, 6.011004, <?php if(isset($mstations['Vaals'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Vaassen', 52.279545, 5.973348, <?php if(isset($mstations['Vaassen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Valkenburg (L)', 50.859927, 5.841674, <?php if(isset($mstations['Valkenburg (L)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Valkenburg', 52.17819, 4.422258, <?php if(isset($mstations['Valkenburg'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Veendam', 53.099214, 6.820503, <?php if(isset($mstations['Veendam'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Veenendaal', 52.029161, 5.591206, <?php if(isset($mstations['Veenendaal'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Veenhuizen (D)', 53.049704, 6.386365, <?php if(isset($mstations['Veenhuizen (D)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Venlo', 51.352428, 6.191099, <?php if(isset($mstations['Venlo'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Venray', 51.515431, 5.992282, <?php if(isset($mstations['Venray'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Vilsteren', 52.528662, 6.359809, <?php if(isset($mstations['Vilsteren'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Vlagtwedde', 53.032391, 7.116479, <?php if(isset($mstations['Vlagtwedde'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Vleuten', 52.091644, 5.007817, <?php if(isset($mstations['Vleuten'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Vlissingen', 51.44, 3.60, <?php if(isset($mstations['Vlissingen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Volkel', 51.660384, 5.705162, <?php if(isset($mstations['Volkel'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Voorschoten', 52.133255, 4.423229, <?php if(isset($mstations['Voorschoten'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Voorthuizen', 52.18193, 5.606527, <?php if(isset($mstations['Voorthuizen'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Vroomshoop', 52.445773, 6.57863, <?php if(isset($mstations['Vroomshoop'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Vrouwenpolder', 51.583986, 3.583542, <?php if(isset($mstations['Vrouwenpolder'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Waalre', 51.364177, 5.444638, <?php if(isset($mstations['Waalre'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Wageningen (Pd)', 51.975117, 5.649176, <?php if(isset($mstations['Wageningen (Pd)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Wapenveld', 52.431772, 6.078293, <?php if(isset($mstations['Wapenveld'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Warffum', 53.398597, 6.559843, <?php if(isset($mstations['Warffum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Weerselo', 52.3526, 6.869713, <?php if(isset($mstations['Weerselo'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Weert', 51.255899, 5.702349, <?php if(isset($mstations['Weert'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Weesp', 52.30744, 5.035302, <?php if(isset($mstations['Weesp'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['West Beemster', 52.585575, 4.900287, <?php if(isset($mstations['West Beemster'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['West Terschelling', 53.368257, 5.221961, <?php if(isset($mstations['West Terschelling'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Westdorpe', 51.219462, 3.869903, <?php if(isset($mstations['Westdorpe'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Westkapelle', 51.527766, 3.441636, <?php if(isset($mstations['Westkapelle'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Wijk aan Zee', 52.49423, 4.621519, <?php if(isset($mstations['Wijk aan Zee'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Wijk bij Duurstede', 51.966398, 5.31445, <?php if(isset($mstations['Wijk bij Duurstede'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Wilhelminadorp', 51.525548, 3.902931, <?php if(isset($mstations['Wilhelminadorp'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallPurple.png'"; } ?>],
['Winschoten', 53.132256, 7.045744, <?php if(isset($mstations['Winschoten'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Winterswijk (Sibinkweg)', 51.95929, 6.682093, <?php if(isset($mstations['Winterswijk (Sibinkweg)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Wolphaartsdijk', 51.532413, 3.744151, <?php if(isset($mstations['Wolphaartsdijk'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Woltersum', 53.271108, 6.721272, <?php if(isset($mstations['Woltersum'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Woold', 51.92269, 6.739192, <?php if(isset($mstations['Woold'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Woudenberg', 52.083243, 5.460151, <?php if(isset($mstations['Woudenberg'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zaandam (Hembrug)', 52.423485, 4.828563, <?php if(isset($mstations['Zaandam (Hembrug)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zaandijk', 52.477337, 4.813164, <?php if(isset($mstations['Zaandijk'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zaltbommel', 51.795586, 5.271237, <?php if(isset($mstations['Zaltbommel'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zandvoort', 52.340638, 4.506775, <?php if(isset($mstations['Zandvoort'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zeerijp', 53.342637, 6.753519, <?php if(isset($mstations['Zeerijp'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zeewolde (Schillinkweg)', 52.298971, 5.416526, <?php if(isset($mstations['Zeewolde (Schillinkweg)'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zeewolde', 52.38885, 5.372517, <?php if(isset($mstations['Zeewolde'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zegveld', 52.135889, 4.832164, <?php if(isset($mstations['Zegveld'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zetten', 51.93898, 5.721676, <?php if(isset($mstations['Zetten'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zoetermeer', 52.071136, 4.526669, <?php if(isset($mstations['Zoetermeer'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zoutkamp', 53.329056, 6.287767, <?php if(isset($mstations['Zoutkamp'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zundert', 51.469838, 4.667591, <?php if(isset($mstations['Zundert'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zweelo', 52.79462, 6.736383, <?php if(isset($mstations['Zweelo'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>],
['Zwolle', 52.530268, 6.138784, <?php if(isset($mstations['Zwolle'])){ echo "'images/BallYellow.png'"; }else{ echo "'images/BallBlue.png'"; } ?>]
];